name: Docker-Cowsay-CI
env:
  DEPLOY_PACKAGE_NAME: "cowsay-app-${{ github.sha }}.zip"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps   :
      
      - name: Git clone repo
        uses: actions/checkout@v1
      
      - name: Create ZIP Deployment package for CD
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
      - name: Build the Docker image
        run : docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
    
      - name : View the Docker Images after build
        run  : docker images
    
      - name : Run the Docker container and Remove after start
        run  : docker run --rm my-image-name:${{ github.sha }}
      
      - name : Remove the Docker image
        run  : docker rmi  my-image-name:${{ github.sha }}
